Task:- 1 import and File Path

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\muham\Downloads\project_4.1\data\samplesuperstore.csv')

Task:- 2 Data Health Inspection

In [3]:
df.shape

(10194, 21)

In [4]:
df.dtypes

Row ID              int64
Order ID           object
Order Date         object
Ship Date          object
Ship Mode          object
Customer ID        object
Customer Name      object
Segment            object
Country/Region     object
City               object
State/Province     object
Postal Code        object
Region             object
Product ID         object
Category           object
Sub-Category       object
Product Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [5]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [6]:
df[["Sales","Quantity","Discount","Profit"]].describe()

              Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

Task:- 3 Check and Remove Duplicate

In [7]:
print("Duplicate Rows:",df.duplicated().sum())
dupes = df[df.duplicated(subset=["Order ID"], keep=False)]
print(dupes.shape)
dupes.head()

Duplicate Rows: 0
(7601, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,1/4/2023,1/8/2023,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
5,6,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,2573.820,9,0.0,746.4078
6,7,US-2023-167199,1/6/2023,1/10/2023,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,42420,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796

Task:- 4 Convert Date Coloumns

In [8]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])
(df.dtypes)

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

Task:- 5 Engineer Shipping Days

In [9]:
df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days
(df.groupby("Region")["Shipping Days"].mean().round(1))

Region
Central    4.1
East       3.9
South      4.0
West       3.9
Name: Shipping Days, dtype: float64

Task:- 7 Engineer Profit Margin

In [10]:
df["Profit Margin"] = (df["Profit"] / df["Sales"] * 100).round(2)
(df.groupby("Sub-Category")["Profit Margin"].mean()
    .sort_values(ascending=True).round(1))

Sub-Category
Binders       -19.5
Appliances    -14.9
Tables        -14.0
Bookcases     -13.5
Machines       -6.9
Chairs          4.7
Storage         9.1
Supplies       11.4
Phones         12.2
Furnishings    14.0
Accessories    21.8
Art            25.2
Fasteners      30.6
Copiers        32.0
Envelopes      42.3
Labels         42.5
Paper          42.5
Name: Profit Margin, dtype: float64

Task:- 6 Engineer Order Year

In [11]:
df["Order Year"] = df["Order Date"].dt.year

In [12]:
(df)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Days,Profit Margin,Order Year
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,4,33.75,2023
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,4,-155.00,2023
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,4,36.25,2023
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,4,-23.75,2023
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,7,25.00,2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,10190,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910,4,37.50,2026
10190,10191,US-2026-115427,2026-12-30,2027-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,Office Supplies,Binders,GBC Binding covers,20.720,2,0.2,6.4750,4,31.25,2026
10191,10192,US-2026-156720,2026-12-30,2027-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,Office Supplies,Fasteners,Bagged Rubber Bands,3.024,3,0.2,-0.6048,4,-20.00,2026
10192,10193,US-2026-143259,2026-12-30,2027-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,Technology,Phones,Gear Head AU3700S Headset,90.930,7,0.0,2.7279,4,3.00,2026
10193,10194,CA-2026-143500,2026-12-30,2027-01-03,Standard Class,HO-15230,Harry Olson,Consumer,Canada,Charlottetown,...,Office Supplies,Binders,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048,4,-20.00,2026

Task:- 8 Rename Coloumns for clean Code

In [13]:
df.rename(columns={"Row ID": "row_id", "Order ID": "order_id","Order Date": "order_date","Ship Date": "ship_date","Ship Mode": "ship_mode","Customer ID": "customer_id","Customer Name": "customer_name","Segment": "segment","Country/Region": "country_region","City": "city","Sub-Category": "sub_category","Product Name": "product_name","Sales": "sales","Quantity": "quantity","Discount": "discount","Profit": "profit","Shipping Days": "shipping_days","Profit Margin": "profit_margin","Order Year": "order_year"}, inplace=True)

In [14]:
(df.dtypes)

row_id                     int64
order_id                  object
order_date        datetime64[ns]
ship_date         datetime64[ns]
ship_mode                 object
customer_id               object
customer_name             object
segment                   object
country_region            object
city                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
sub_category              object
product_name              object
sales                    float64
quantity                   int64
discount                 float64
profit                   float64
shipping_days              int64
profit_margin            float64
order_year                 int32
dtype: object

Task:- 9 Final inspection and export

In [15]:
df.to_csv(r'C:\Users\muham\Downloads\project_4.1\data\cleaned_superstore.csv', index=False)
check = pd.read_csv(r"C:\Users\muham\Downloads\project_4.1\data\cleaned_superstore.csv")
print("saved Shape:", check.shape)

saved Shape: (10194, 24)